"""`plutus bootstrap`: generate ``.plutus/manifest.yaml.draft`` from results.json.

Reads ``.plutus/run/<step_id>/results.json`` files left behind by
``pv.step(...)`` invocations, plus a few filesystem signals
(``.python-version``, ``pyproject.toml``, ``requirements.txt``), and
emits a partially-filled manifest draft. Fields that can be discovered
mechanically (schema_version, env.python_version, env.requirements_file,
repo.name, per-step ``outputs``, ``expected.metrics``,
``expected.reference_outputs``) are auto-filled. Fields requiring domain
knowledge (``env.os_packages``, ``secrets``, ``data_sources``,
per-step ``command`` / ``nine_step`` / ``inputs`` / ``depends_on``,
``nine_step_coverage``) are marked with grep-friendly ``TODO_*`` sentinels.

A separate ``manifest_TODO.md`` doc (populated in Task 3) walks the
author through what each TODO marker means.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from plutus_verify.spec.runtime.results import load_results

# ---------------------------------------------------------------------------
# Detection helpers
# ---------------------------------------------------------------------------

_PY_VERSION_RE = re.compile(r"(\d+\.\d+)")
_REQUIRES_PYTHON_RE = re.compile(r"""requires-python\s*=\s*["'](.*?)["']""")


def _detect_python_version(repo_path: Path) -> str:
    """Return ``major.minor`` like ``"3.11"``.

    Resolution order:
      1. ``.python-version`` (first non-empty line; truncated to ``M.N``).
      2. ``pyproject.toml`` ``[project] requires-python`` (first ``M.N`` match).
      3. Fallback ``"3.11"``.
    """
    pv_file = repo_path / ".python-version"
    if pv_file.exists():
        try:
            text = pv_file.read_text().strip()
        except OSError:
            text = ""
        if text:
            first = text.splitlines()[0].strip()
            match = _PY_VERSION_RE.search(first)
            if match:
                return match.group(1)

    pyproject = repo_path / "pyproject.toml"
    if pyproject.exists():
        try:
            text = pyproject.read_text()
        except OSError:
            text = ""
        rp_match = _REQUIRES_PYTHON_RE.search(text)
        if rp_match:
            inner = rp_match.group(1)
            mn_match = _PY_VERSION_RE.search(inner)
            if mn_match:
                return mn_match.group(1)

    return "3.11"


def _detect_requirements_file(repo_path: Path) -> Optional[str]:
    """Return ``"requirements.txt"`` if present, else ``None``."""
    if (repo_path / "requirements.txt").exists():
        return "requirements.txt"
    return None


def _detect_repo_name(repo_path: Path) -> str:
    """Return the resolved directory name (handles ``.`` and trailing slash)."""
    return Path(repo_path).resolve().name


def _to_display_name(name: str) -> str:
    """Convert ``sharpe_ratio`` → ``Sharpe Ratio``.

    Title-case each underscore-separated token. Empty tokens are dropped.
    """
    parts = [p for p in name.split("_") if p]
    return " ".join(p[:1].upper() + p[1:] for p in parts)


def _artifact_compare_kind(artifact_kind: str) -> str:
    """Map a results.json artifact ``kind`` to a manifest ``compare`` strategy."""
    if artifact_kind in ("chart", "image"):
        return "visual_similarity"
    if artifact_kind == "json":
        return "json_numeric_tolerance"
    # csv | other | anything else
    return "byte_exact"


# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------

_HEADER = (
    "Generated by `plutus bootstrap` from .plutus/run/. Fill in TODO_* markers,\n"
    "rename to manifest.yaml, then `plutus check`. See manifest_TODO.md for guidance."
)

_TODO_PLACEHOLDER = (
    "# Plutus manifest TODO checklist\n"
    "\n"
    "TODO: Task 3 will populate this.\n"
)


class BootstrapError(RuntimeError):
    """Failed to bootstrap a manifest draft."""


@dataclass(frozen=True)
class BootstrapResult:
    draft_path: Path
    todo_path: Path
    steps_with_metrics: int
    metrics_total: int
    notes: list[str] = field(default_factory=list)


def _flow(map_: CommentedMap) -> CommentedMap:
    """Force flow style on a ``CommentedMap`` (returns the same instance)."""
    map_.fa.set_flow_style()
    return map_


def _build_manifest_dict(
    repo_path: Path,
    step_ids: list[str],
) -> tuple[CommentedMap, int, int]:
    """Construct the draft manifest CommentedMap.

    Returns ``(data, steps_with_metrics, metrics_total)``.
    """
    py_version = _detect_python_version(repo_path)
    req_file = _detect_requirements_file(repo_path)
    repo_name = _detect_repo_name(repo_path)

    data = CommentedMap()

    # schema_version
    data["schema_version"] = "2.0"

    # repo
    repo_block = CommentedMap()
    repo_block["name"] = repo_name
    repo_block["primary_language"] = "python"
    data["repo"] = repo_block

    # env
    env_block = CommentedMap()
    env_block["base"] = "python"
    env_block["python_version"] = py_version
    env_block["requirements_file"] = req_file  # may be None
    env_block["os_packages"] = CommentedSeq()
    env_block.yaml_add_eol_comment(
        "TODO_os_packages: list apt packages your deps need", "os_packages"
    )
    data["env"] = env_block

    # secrets
    data["secrets"] = CommentedSeq()
    data.yaml_add_eol_comment(
        "TODO_secrets: declare env vars (see manifest_TODO.md)", "secrets"
    )

    # data_sources
    ds_block = CommentedMap()
    ds_block["processed"] = CommentedSeq()
    ds_block["raw"] = CommentedSeq()
    data["data_sources"] = ds_block
    data.yaml_set_comment_before_after_key(
        "data_sources",
        after=(
            "TODO_data_sources: declare downloadable data (see manifest_TODO.md)"
        ),
        after_indent=2,
    )

    # steps
    steps_seq = CommentedSeq()
    for step_id in step_ids:
        try:
            results = load_results(repo_path, step_id=step_id)
            artifact_paths = [a.path for a in results.artifacts]
        except Exception:
            artifact_paths = []

        step_map = CommentedMap()
        step_map["id"] = step_id
        step_map["nine_step"] = f"TODO_nine_step_for_{step_id}"
        step_map["required"] = True
        step_map["network"] = "none"
        step_map["timeout_seconds"] = 1800
        step_map["command"] = f"TODO_command_for_{step_id}"
        step_map["inputs"] = CommentedSeq()
        step_map.yaml_add_eol_comment(
            f"TODO_inputs_for_{step_id}", "inputs"
        )
        outputs_seq = CommentedSeq()
        for path in artifact_paths:
            outputs_seq.append(path)
        step_map["outputs"] = outputs_seq
        step_map["depends_on"] = CommentedSeq()
        step_map.yaml_add_eol_comment(
            f"TODO_depends_on_for_{step_id}", "depends_on"
        )
        steps_seq.append(step_map)

    data["steps"] = steps_seq
    data.yaml_set_comment_before_after_key(
        "steps",
        after=(
            "TODO_steps: add data_collection / data_processing / optimization "
            "steps\nthat don't run pv.step (see manifest_TODO.md)"
        ),
        after_indent=2,
    )

    # expected
    expected_seq = CommentedSeq()
    steps_with_metrics = 0
    metrics_total = 0
    for step_id in step_ids:
        try:
            results = load_results(repo_path, step_id=step_id)
        except Exception:
            continue

        expected_block = CommentedMap()
        expected_block["step_id"] = step_id

        metrics_seq = CommentedSeq()
        for metric in results.metrics:
            m_map = CommentedMap()
            m_map["name"] = metric.name
            m_map["display_name"] = _to_display_name(metric.name)
            m_map["value"] = metric.value
            tol = CommentedMap()
            tol["kind"] = "relative"
            tol["value"] = 0.05
            m_map["tolerance"] = _flow(tol)
            metrics_seq.append(m_map)
            metrics_total += 1
        expected_block["metrics"] = metrics_seq

        ref_seq = CommentedSeq()
        for artifact in results.artifacts:
            r_map = CommentedMap()
            r_map["path"] = artifact.path
            r_map["compare"] = _artifact_compare_kind(artifact.kind)
            ref_seq.append(r_map)
        expected_block["reference_outputs"] = ref_seq

        if results.metrics:
            steps_with_metrics += 1

        expected_seq.append(expected_block)

    data["expected"] = expected_seq

    # nine_step_coverage
    coverage = CommentedMap()
    for key in (
        "step_1_hypothesis",
        "step_2_data_collection",
        "step_3_data_processing",
        "step_4_in_sample",
        "step_5_optimization",
        "step_6_out_of_sample",
        "step_7_paper_trading",
    ):
        inner = CommentedMap()
        inner["present"] = False
        inner["section"] = None
        coverage[key] = _flow(inner)
    data["nine_step_coverage"] = coverage
    data.yaml_set_comment_before_after_key(
        "nine_step_coverage",
        after=(
            "TODO_nine_step_coverage: set present:true and the README section heading"
        ),
        after_indent=2,
    )

    return data, steps_with_metrics, metrics_total


def _make_yaml() -> YAML:
    yaml = YAML(typ="rt")
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.width = 4096
    return yaml


def scaffold_bootstrap(
    repo_path: Path,
    *,
    force: bool = False,
) -> BootstrapResult:
    """Generate ``.plutus/manifest.yaml.draft`` + ``.plutus/manifest_TODO.md``.

    Reads ``<repo>/.plutus/run/<step_id>/results.json`` files written by the
    SDK, derives a partially-filled manifest with grep-friendly ``TODO_*``
    sentinels for fields requiring domain knowledge, and writes the draft.

    Raises:
        BootstrapError: if a real ``manifest.yaml`` already exists, if the
            draft or TODO file exists and ``force`` is False, or if no
            results.json files are found.
    """
    repo_path = Path(repo_path)
    plutus_dir = repo_path / ".plutus"

    manifest_path = plutus_dir / "manifest.yaml"
    draft_path = plutus_dir / "manifest.yaml.draft"
    todo_path = plutus_dir / "manifest_TODO.md"

    if manifest_path.exists():
        raise BootstrapError(
            f"manifest.yaml already exists at {manifest_path}; bootstrap is "
            "for the pre-manifest stage. Remove it or use a different repo."
        )

    if draft_path.exists() and not force:
        raise BootstrapError(
            f"manifest.yaml.draft already exists at {draft_path}; "
            "pass force=True to overwrite."
        )

    if todo_path.exists() and not force:
        raise BootstrapError(
            f"manifest_TODO.md already exists at {todo_path}; "
            "pass force=True to overwrite."
        )

    run_root = plutus_dir / "run"
    results_files = sorted(run_root.glob("*/results.json")) if run_root.exists() else []
    if not results_files:
        raise BootstrapError(
            f"no results.json files found under .plutus/run/ in {repo_path}. "
            "Instrument your scripts with `pv.step(...)` and run them once "
            "before bootstrap."
        )

    step_ids = sorted({p.parent.name for p in results_files})

    notes: list[str] = []
    data, steps_with_metrics, metrics_total = _build_manifest_dict(repo_path, step_ids)

    # Attach the top-of-file header comment.
    data.yaml_set_start_comment(_HEADER)

    # Make sure the .plutus dir exists (it does — results.json lives under it,
    # but be defensive in case of an unusual layout).
    plutus_dir.mkdir(parents=True, exist_ok=True)

    yaml = _make_yaml()
    with draft_path.open("w") as f:
        yaml.dump(data, f)

    todo_path.write_text(_TODO_PLACEHOLDER)

    return BootstrapResult(
        draft_path=draft_path,
        todo_path=todo_path,
        steps_with_metrics=steps_with_metrics,
        metrics_total=metrics_total,
        notes=notes,
    )
