"""Tests for the real Docker image builder."""
import subprocess
from pathlib import Path

import pytest

from plutus_verify.spec.runtime.real_image_builder import (
    BuildError,
    build_image,
    ensure_dockerignore,
    make_image_builder,
)


_DOCKERFILE = "FROM python:3.11-slim\nWORKDIR /srv/repo\n"


def test_build_image_writes_dockerfile_and_invokes_docker(tmp_path: Path):
    calls = []

    def fake_runner(cmd, cwd):
        calls.append((cmd, cwd))
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    tag = build_image(_DOCKERFILE, tmp_path, docker_runner=fake_runner)

    # Tag is deterministic and digest-based
    assert tag.startswith("plutus-v2:")
    assert len(tag.split(":")[1]) == 12

    # Dockerfile got written to .plutus/Dockerfile.generated
    df = tmp_path / ".plutus" / "Dockerfile.generated"
    assert df.exists()
    assert df.read_text() == _DOCKERFILE

    # Exactly one docker invocation, with the expected args
    assert len(calls) == 1
    cmd, cwd = calls[0]
    assert cmd[:2] == ["docker", "build"]
    assert "--tag" in cmd
    assert tag in cmd
    assert "--file" in cmd
    assert str(df) in cmd
    assert str(tmp_path) in cmd
    assert cwd == tmp_path


def test_build_image_raises_build_error_on_nonzero_exit(tmp_path: Path):
    def failing_runner(cmd, cwd):
        return subprocess.CompletedProcess(
            args=cmd, returncode=1, stdout="building...", stderr="error: missing layer",
        )

    with pytest.raises(BuildError, match="exit 1"):
        build_image(_DOCKERFILE, tmp_path, docker_runner=failing_runner)


def test_build_image_includes_stderr_tail_in_error(tmp_path: Path):
    def failing_runner(cmd, cwd):
        return subprocess.CompletedProcess(
            args=cmd, returncode=2, stdout="", stderr="specific failure mode XYZ",
        )

    with pytest.raises(BuildError, match="specific failure mode XYZ"):
        build_image(_DOCKERFILE, tmp_path, docker_runner=failing_runner)


def test_image_tag_is_content_addressed(tmp_path: Path):
    def ok_runner(cmd, cwd):
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    tag1 = build_image(_DOCKERFILE, tmp_path, docker_runner=ok_runner)
    tag2 = build_image(_DOCKERFILE, tmp_path, docker_runner=ok_runner)
    assert tag1 == tag2

    tag3 = build_image(_DOCKERFILE + "RUN echo hi\n", tmp_path, docker_runner=ok_runner)
    assert tag3 != tag1


def test_make_image_builder_returns_callable(tmp_path: Path, monkeypatch):
    # Patch the default docker runner to avoid invoking real docker
    def fake(cmd, cwd):
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    monkeypatch.setattr(
        "plutus_verify.spec.runtime.real_image_builder._default_docker_runner",
        fake,
    )

    builder = make_image_builder(image_prefix="custom-pre")
    tag = builder(_DOCKERFILE, tmp_path)
    assert tag.startswith("custom-pre:")


# ---------------------------------------------------------------------------
# .dockerignore baseline (0.2.9+)
# ---------------------------------------------------------------------------

def test_ensure_dockerignore_writes_when_absent(tmp_path: Path):
    """Repo with no .dockerignore gets the baseline written; helper returns True."""
    assert not (tmp_path / ".dockerignore").exists()
    wrote = ensure_dockerignore(tmp_path)
    assert wrote is True
    content = (tmp_path / ".dockerignore").read_text()
    # Spot-check the security-critical entries — these are why the baseline exists.
    assert ".env\n" in content
    assert ".env.local\n" in content
    assert ".env.*.local\n" in content
    assert ".git/\n" in content
    assert ".plutus/run/\n" in content
    assert ".plutus/results/\n" in content  # per-run harvest buffer (L2): must not leak into image
    assert ".plutus/cache/\n" in content    # data download cache (Bug 3): must not leak into image
    assert ".plutus/build/\n" in content
    # Auto-generated marker so future readers know the source.
    assert "Auto-generated by plutus-verify" in content


def test_baseline_unexcludes_sdk_wheel_inside_plutus_build(tmp_path: Path):
    """`.plutus/build/` is excluded but the SDK wheel is re-included.

    Regression guard: the framework's own `Dockerfile.generated` does
    `COPY .plutus/build/plutus_verify-*.whl /tmp/...`. If the baseline
    excludes `.plutus/build/` without a negate for the wheel, every
    fresh `plutus check` against a wheel-staged repo fails at build
    time with `CopyIgnoredFile`. The negate pattern must come AFTER
    the parent exclude to take effect.
    """
    ensure_dockerignore(tmp_path)
    content = (tmp_path / ".dockerignore").read_text()
    lines = content.splitlines()
    build_excl_idx = lines.index(".plutus/build/")
    wheel_negate_idx = lines.index("!.plutus/build/plutus_verify-*.whl")
    assert wheel_negate_idx > build_excl_idx, (
        "negate pattern must follow the parent exclude to take effect"
    )


def test_ensure_dockerignore_preserves_existing_file(tmp_path: Path):
    """User-authored .dockerignore wins — helper returns False, content untouched."""
    sentinel = "# user-authored sentinel\nuser-specific-pattern/\n"
    (tmp_path / ".dockerignore").write_text(sentinel)
    wrote = ensure_dockerignore(tmp_path)
    assert wrote is False
    assert (tmp_path / ".dockerignore").read_text() == sentinel


def test_build_image_writes_dockerignore_alongside_dockerfile(tmp_path: Path):
    """build_image() seeds .dockerignore as part of build-context prep.

    Closes the cache-leak / secret-leak class of issue: without this, a
    `COPY . .` against a repo containing `.env` or stale `.plutus/run/`
    caches would bake them into the image.
    """
    def fake_runner(cmd, cwd):
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    build_image(_DOCKERFILE, tmp_path, docker_runner=fake_runner)

    dockerignore = tmp_path / ".dockerignore"
    assert dockerignore.exists(), "build_image must seed .dockerignore"
    content = dockerignore.read_text()
    # The two files that motivated this fix:
    assert ".env\n" in content      # secret leak
    assert ".git/\n" in content     # vcs leak
    assert ".plutus/run/\n" in content  # cache leak


def test_build_image_does_not_overwrite_existing_dockerignore(tmp_path: Path):
    """Pre-existing .dockerignore survives a build invocation."""
    sentinel = "# user-authored\nmy-secret-dir/\n"
    (tmp_path / ".dockerignore").write_text(sentinel)

    def fake_runner(cmd, cwd):
        return subprocess.CompletedProcess(args=cmd, returncode=0, stdout="", stderr="")

    build_image(_DOCKERFILE, tmp_path, docker_runner=fake_runner)

    assert (tmp_path / ".dockerignore").read_text() == sentinel
